struct AppRating
{
    std::string desktopId;       // .desktop file name without extension
    std::string execContains;    // substring to match in the Exec line
    int popularity;              // positive for popular apps, negative for penalty
};

const std::vector<AppRating> GlobalPopularity =
{
    // ── Browsers ──
    {"firefox",                      "firefox",            100},
    {"zen",                          "zen",                 95},
    {"google-chrome",                "google-chrome",       95},
    {"chromium-browser",             "chromium",            90},
    {"brave-browser",                "brave",               85},
    {"vivaldi-stable",               "vivaldi",             80},
    {"librewolf",                    "librewolf",           75},
    {"microsoft-edge",               "microsoft-edge",      70},
    {"floorp",                       "floorp",              65},
    {"tor-browser",                  "tor-browser",         65},
    {"opera",                        "opera",               60},
    {"waterfox",                     "waterfox",            55},
    {"palemoon",                     "palemoon",            50},

    // ── Code Editors & IDEs ──
    {"code",                         "code",               100},
    {"nvim",                         "nvim",                90},
    {"vim",                          "gvim",                85},
    {"codium",                       "codium",              80},
    {"sublime_text",                 "sublime_text",        80},
    {"jetbrains-pycharm",            "pycharm",             90},
    {"jetbrains-idea",               "idea",                85},
    {"emacs",                        "emacs",               75},
    {"dev.zed.Zed",                  "zed",                 75},
    {"helix",                        "helix",               75},
    {"jetbrains-webstorm",           "webstorm",            75},
    {"jetbrains-clion",              "clion",               75},
    {"jetbrains-goland",             "goland",              70},
    {"jetbrains-phpstorm",           "phpstorm",            70},
    {"geany",                        "geany",               65},
    {"kate",                         "kate",                70},
    {"gedit",                        "gedit",               70},
    {"nano",                         "nano",                70},
    {"micro",                        "micro",               70},
    {"mousepad",                     "mousepad",            65},
    {"jetbrains-rider",              "rider",               65},
    {"jetbrains-datagrip",           "datagrip",            65},
    {"notepadqq",                    "notepadqq",           60},
    {"kakoune",                      "kak",                 60},
    {"leafpad",                      "leafpad",             55},
    {"vscode-insiders",              "code-insiders",       50},

    // ── Terminals ──
    {"alacritty",                    "alacritty",           95},
    {"kitty",                        "kitty",               90},
    {"org.kde.konsole",              "konsole",             85},
    {"org.gnome.Terminal",           "gnome-terminal",      85},
    {"com.mitchellh.ghostty",        "ghostty",             80},
    {"xfce4-terminal",               "xfce4-terminal",      75},
    {"foot",                         "foot",                75},
    {"org.wezfurlong.wezterm",       "wezterm",             75},
    {"com.gexperts.Tilix",           "tilix",               70},
    {"terminator",                   "terminator",          70},
    {"rxvt-unicode",                 "urxvt",               65},
    {"st",                           "st",                  60},
    {"cool-retro-term",              "cool-retro-term",     55},
    {"hyper",                        "hyper",               50},
    {"termite",                      "termite",             55},

    // ── Communication ──
    {"discord",                      "discord",             95},
    {"org.telegram.desktop",         "telegram",            90},
    {"slack",                        "slack",               80},
    {"us.zoom.Zoom",                 "zoom",                80},
    {"signal-desktop",               "signal-desktop",      75},
    {"teams-for-linux",              "teams",               75},
    {"vesktop",                      "vesktop",             70},
    {"element-desktop",              "element",             60},
    {"skypeforlinux",                "skype",               60},
    {"whatsapp-desktop",             "whatsapp",            55},
    {"mattermost-desktop",           "mattermost",          60},
    {"rocketchat-desktop",           "rocketchat",          55},
    {"wire-desktop",                 "wire",                55},
    {"jami",                         "jami",                50},
    {"session-desktop",              "session",             50},

    // ── Gaming ──
    {"steam",                        "steam",              100},
    {"net.lutris.Lutris",            "lutris",              85},
    {"minecraft-launcher",           "minecraft-launcher",  80},
    {"heroic",                       "heroic",              75},
    {"org.prismlauncher.PrismLauncher", "prismlauncher",    75},
    {"com.usebottles.bottles",       "bottles",             75},
    {"org.libretro.RetroArch",       "retroarch",           70},
    {"dolphin-emu",                  "dolphin-emu",         60},
    {"yuzu",                         "yuzu",                65},
    {"ryujinx",                      "ryujinx",             60},
    {"pcsx2",                        "pcsx2",               55},
    {"rpcs3",                        "rpcs3",               55},
    {"cemu",                         "cemu",                50},
    {"playonlinux",                  "playonlinux",         55},
    {"winecfg",                      "winecfg",             65},

    // ── Multimedia ──
    {"vlc",                          "vlc",                 95},
    {"mpv",                          "mpv",                 90},
    {"spotify",                      "spotify",             90},
    {"com.obsproject.Studio",        "obs",                 85},
    {"audacity",                     "audacity",            80},
    {"org.kde.kdenlive",             "kdenlive",            80},
    {"org.musescore.MuseScore",      "musescore",           75},
    {"audacious",                    "audacious",           70},
    {"rhythmbox",                    "rhythmbox",           70},
    {"strawberry",                   "strawberry",          70},
    {"org.shotcut.Shotcut",          "shotcut",             70},
    {"org.openshot.OpenShot",        "openshot",            65},
    {"clementine",                   "clementine",          65},
    {"deadbeef",                     "deadbeef",            65},
    {"cmus",                         "cmus",                65},
    {"simplescreenrecorder",         "simplescreenrecorder", 65},
    {"org.ksnip.ksnip",             "ksnip",               65},
    {"com.uploadedlobster.peek",     "peek",                60},
    {"ncmpcpp",                      "ncmpcpp",             60},
    {"elisa",                        "elisa",               60},
    {"davinci-resolve",              "davinci-resolve",     60},
    {"amarok",                       "amarok",              60},
    {"cantata",                      "cantata",             55},
    {"lmms",                         "lmms",                55},
    {"org.olivevideoeditor.Olive",   "olive-editor",        55},
    {"ardour",                       "ardour",              55},
    {"guitarix",                     "guitarix",            50},
    {"hydrogen",                     "hydrogen",            55},
    {"easyeffects",                  "easyeffects",         60},   // Easy Effects (PipeWire)
    {"xmms",                         "xmms",                50},   // legacy audio player
    {"winff",                        "winff",               50},   // video converter

    // ── Graphics ──
    {"gimp",                         "gimp",                90},
    {"blender",                      "blender",             85},
    {"org.kde.krita",                "krita",               80},
    {"org.inkscape.Inkscape",        "inkscape",            80},
    {"org.darktable.Darktable",      "darktable",           70},
    {"org.kde.digikam",              "digikam",             65},
    {"rawtherapee",                  "rawtherapee",         60},
    {"pinta",                        "pinta",               60},
    {"aseprite",                     "aseprite",            60},
    {"mypaint",                      "mypaint",             55},
    {"scribus",                      "scribus",             60},
    {"com.github.xournalpp.xournalpp", "xournalpp",         70},
    {"com.github.flxzt.rnote",       "rnote",               65},
    {"kolourpaint",                  "kolourpaint",         60},
    {"synfigstudio",                 "synfigstudio",        55},
    {"natron",                       "natron",              50},
    {"grafx2",                       "grafx2",              50},
    {"mirage",                       "mirage",              55},   // image viewer

    // ── File Managers ──
    {"org.kde.dolphin",              "dolphin",             90},
    {"thunar",                       "thunar",              85},
    {"org.gnome.Nautilus",           "nautilus",            85},
    {"pcmanfm",                      "pcmanfm",             75},
    {"nemo",                         "nemo",                65},
    {"caja",                         "caja",                65},
    {"ranger",                       "ranger",              70},
    {"doublecmd",                    "doublecmd",           65},
    {"mc",                           "mc",                  65},
    {"pcmanfm-qt",                   "pcmanfm-qt",          70},
    {"nnn",                          "nnn",                 65},
    {"lf",                           "lf",                  60},
    {"spacefm",                      "spacefm",             60},
    {"org.kde.krusader",             "krusader",            60},
    {"vifm",                         "vifm",                60},
    {"fman",                         "fman",                50},

    // ── Development Tools ──
    {"postman",                      "postman",             80},
    {"dbeaver",                      "dbeaver",             75},
    {"gitkraken",                    "gitkraken",           75},
    {"virt-manager",                 "virt-manager",        80},
    {"virtualbox",                   "virtualbox",          75},
    {"insomnia",                     "insomnia",            65},
    {"docker-desktop",               "docker-desktop",      70},
    {"smartgit",                     "smartgit",            70},
    {"sublime_merge",                "sublime_merge",       65},
    {"git-cola",                     "git-cola",            60},
    {"org.gnome.gitg",               "gitg",                65},
    {"mysql-workbench",              "mysql-workbench",     60},
    {"pgadmin4",                     "pgadmin4",            65},
    {"sqlitebrowser",                "sqlitebrowser",       70},
    {"org.gnome.Boxes",              "gnome-boxes",         65},
    {"org.remmina.Remmina",          "remmina",             80},
    {"filezilla",                    "filezilla",           70},
    {"wireshark",                    "wireshark",           70},
    {"zenmap",                       "zenmap",              55},
    {"mongodb-compass",              "mongodb-compass",     60},
    {"robo3t",                       "robo3t",              50},
    {"meld",                         "meld",                70},   // diff/merge tool

    // ── System Utilities ──
    {"htop",                         "htop",                85},
    {"btop",                         "btop",                80},
    {"fastfetch",                    "fastfetch",           75},
    {"flameshot",                    "flameshot",           80},
    {"gparted",                      "gparted",             75},
    {"timeshift-gtk",                "timeshift-gtk",       70},
    {"org.gnome.SystemMonitor",      "gnome-system-monitor", 70},
    {"org.gnome.DiskUtility",        "gnome-disks",         70},
    {"org.kde.ksysguard",            "ksysguard",           65},
    {"neofetch",                     "neofetch",            65},
    {"org.kde.spectacle",            "spectacle",           70},
    {"redshift-gtk",                 "redshift-gtk",        65},
    {"conky",                        "conky",               60},
    {"nitrogen",                     "nitrogen",            60},
    {"feh",                          "feh",                 70},
    {"glances",                      "glances",             60},
    {"iotop",                        "iotop",               60},
    {"iftop",                        "iftop",               55},
    {"bpytop",                       "bpytop",              60},
    {"pavucontrol",                  "pavucontrol",         70},
    {"blueman",                      "blueman",             65},
    {"org.gnome.tweaks",             "gnome-tweaks",        65},
    {"lxappearance",                 "lxappearance",        55},
    {"kvantummanager",               "kvantum",             55},
    {"variety",                      "variety",             55},
    {"pywal",                        "pywal",               60},
    {"synaptic",                     "synaptic",            75},   // package manager
    {"grsync",                       "grsync",              60},   // rsync GUI
    {"arandr",                       "arandr",              60},   // monitor settings
    {"clipit",                       "clipit",              60},   // clipboard manager
    {"luckybackup",                  "luckybackup",         55},   // backup tool

    // ── AI Tools ──
    {"chatgpt-desktop",              "chatgpt",             80},
    {"lm-studio",                    "lm-studio",           75},
    {"jan",                          "jan",                 70},
    {"gpt4all",                      "gpt4all",             65},
    {"anythingllm",                  "anythingllm",         60},
    {"ollama",                       "ollama",              60},
    {"alpaca",                       "alpaca",              55},

    // ── Office & Productivity ──
    {"libreoffice-startcenter",      "libreoffice",         90},
    {"lowriter",                     "lowriter",            85},
    {"localc",                       "localc",              80},
    {"loimpress",                    "loimpress",           75},
    {"onlyoffice-desktopeditors",    "onlyoffice",          75},
    {"org.gnome.Evince",             "evince",              80},
    {"org.kde.okular",               "okular",              80},
    {"org.pwmt.zathura",             "zathura",             70},
    {"calibre",                      "calibre",             75},
    {"wps",                          "wps",                 65},
    {"mupdf",                        "mupdf",               60},
    {"xreader",                      "xreader",             65},
    {"atril",                        "atril",               65},
    {"com.github.johnfactotum.Foliate", "foliate",          65},
    {"fbreader",                     "fbreader",            60},
    {"app.koodo.KoodoReader",        "koodo-reader",        60},
    {"lodraw",                       "lodraw",              65},
    {"lobase",                       "lobase",              60},
    {"lomath",                       "lomath",              55},
    {"abiword",                      "abiword",             55},
    {"gnumeric",                     "gnumeric",            55},

    // ── Note‑taking & Markdown ──
    {"obsidian",                     "obsidian",            90},
    {"joplin",                       "joplin",              80},
    {"logseq",                       "logseq",              75},
    {"marktext",                     "marktext",            70},
    {"cherrytree",                   "cherrytree",          65},
    {"trilium",                      "trilium",             65},
    {"com.pbek.qownnotes",           "qownnotes",           60},
    {"zim",                          "zim",                 60},
    {"simplenote",                   "simplenote",          60},
    {"org.standardnotes.standardnotes", "standard-notes",   60},
    {"typora",                       "typora",              65},
    {"notable",                      "notable",             55},
    {"boostnote",                    "boostnote",           55},

    // ── Email ──
    {"thunderbird",                  "thunderbird",         90},
    {"evolution",                    "evolution",           70},
    {"betterbird",                   "betterbird",          70},
    {"mailspring",                   "mailspring",          65},
    {"org.kde.kmail2",               "kmail",               65},
    {"org.gnome.Geary",              "geary",               65},
    {"claws-mail",                   "claws-mail",          60},
    {"neomutt",                      "neomutt",             65},
    {"aerc",                         "aerc",                60},
    {"mutt",                         "mutt",                60},
    {"sylpheed",                     "sylpheed",            55},
    {"trojita",                      "trojita",             55},

    // ── Password Managers ──
    {"org.keepassxc.KeePassXC",      "keepassxc",           85},
    {"bitwarden",                    "bitwarden",           80},
    {"authy",                        "authy",               60},
    {"enpass",                       "enpass",              60},
    {"1password",                    "1password",           60},
    {"lesspass",                     "lesspass",            50},

    // ── Cloud & Sync ──
    {"dropbox",                      "dropbox",             75},
    {"nextcloud",                    "nextcloud",           70},
    {"pcloud",                       "pcloud",              65},
    {"insync",                       "insync",              60},
    {"megasync",                     "megasync",            60},
    {"syncthing",                    "syncthing",           65},
    {"syncthing-gtk",                "syncthing-gtk",       60},
    {"org.borgbase.Vorta",           "vorta",               65},
    {"org.gnome.DejaDup",            "deja-dup",            65},
    {"backintime-qt",                "backintime",          60},

    // ── VPN ──
    {"protonvpn",                    "protonvpn",           80},
    {"mullvad",                      "mullvad",             80},
    {"windscribe",                   "windscribe",          65},

    // ── Torrent ──
    {"org.qbittorrent.qBittorrent",  "qbittorrent",         80},
    {"transmission-gtk",             "transmission-gtk",    75},
    {"deluge",                       "deluge",              70},
    {"org.kde.ktorrent",             "ktorrent",            65},
    {"jdownloader",                  "jdownloader",         60},
    {"uget",                         "uget",                55},

    // ── Calculators ──
    {"org.gnome.Calculator",         "gnome-calculator",    75},
    {"qalculate-gtk",                "qalculate",           65},
    {"org.kde.kcalc",                "kcalc",               70},
    {"galculator",                   "galculator",          70},
    {"speedcrunch",                  "speedcrunch",         60},

    // ── Image Viewers ──
    {"org.kde.gwenview",             "gwenview",            70},
    {"gthumb",                       "gthumb",              65},
    {"org.gnome.eog",                "eog",                 65},
    {"geeqie",                       "geeqie",              60},
    {"sxiv",                         "sxiv",                60},
    {"nsxiv",                        "nsxiv",               60},
    {"nomacs",                       "nomacs",              60},

    // ── Audio Players (non‑streaming) ──
    {"deadbeef",                     "deadbeef",            65},
    {"strawberry",                   "strawberry",          70},
    {"audacious",                    "audacious",           70},
    {"rhythmbox",                    "rhythmbox",           70},

    // ── Archivers ──
    {"org.gnome.FileRoller",         "file-roller",         60},
    {"org.kde.ark",                  "ark",                 65},
    {"peazip",                       "peazip",              55},
    {"xarchiver",                    "xarchiver",           50},

    // ── System Settings ──
    {"gnome-control-center",         "gnome-control-center", 85},
    {"systemsettings",               "systemsettings",      80},
    {"xfce4-settings-manager",       "xfce4-settings-manager", 65},
    {"mate-control-center",          "mate-control-center", 60},
    {"lxqt-config",                  "lxqt-config",         55},

    // ── Other Widely Used Apps ──
    {"org.gnome.seahorse.Application", "seahorse",          60},
    {"gucharmap",                    "gucharmap",           50},
    {"org.gnome.Characters",         "gnome-characters",    55},
    {"org.gnome.baobab",             "baobab",              65},
    {"bleachbit",                    "bleachbit",           55},
    {"stacer",                       "stacer",              60},
    {"cpu-x",                        "cpu-x",               55},
    {"hardinfo",                     "hardinfo",            55},
    {"org.gnome.Weather",            "gnome-weather",       50},
    {"cmatrix",                      "cmatrix",             50}
};

const std::vector<AppRating> PenaltyPrograms =
{
    // ── X11 legacy utilities ──
    {"xterm",                        "xterm",              -300},
    {"uxterm",                       "uxterm",             -300},
    {"xmessage",                     "xmessage",           -300},
    {"xclock",                       "xclock",             -300},
    {"xfontsel",                     "xfontsel",           -300},
    {"xcalc",                        "xcalc",              -300},
    {"xclipboard",                   "xclipboard",         -300},
    {"xmag",                         "xmag",               -300},
    {"xedit",                        "xedit",              -300},
    {"xeyes",                        "xeyes",              -300},
    {"xlogo",                        "xlogo",              -300},
    {"xgc",                          "xgc",                -300},
    {"xev",                          "xev",                -300},
    {"xprop",                        "xprop",              -300},
    {"xwininfo",                     "xwininfo",           -300},
    {"xdpyinfo",                     "xdpyinfo",           -300},
    {"xrandr",                       "xrandr",             -200},
    {"xinput",                       "xinput",             -200},
    {"xset",                         "xset",               -200},
    {"xgamma",                       "xgamma",             -300},
    {"xmodmap",                      "xmodmap",            -300},
    {"xkill",                        "xkill",              -300},
    {"xrefresh",                     "xrefresh",           -300},
    {"xwd",                          "xwd",                -300},
    {"xwud",                         "xwud",               -300},
    {"xauth",                        "xauth",              -300},
    {"xhost",                        "xhost",              -300},
    {"xrdb",                         "xrdb",               -300},
    {"xsetroot",                     "xsetroot",           -300},
    {"xcursorgen",                   "xcursorgen",         -300},
    {"xdg-screensaver",              "xdg-screensaver",    -300},
    {"xdg-open",                     "xdg-open",           -200},

    // ── Accessibility ──
    {"orca",                         "orca",               -200},

    // ── Printing ──
    {"system-config-printer",        "system-config-printer", -200},
    {"hp-toolbox",                   "hp-toolbox",         -200},
    {"hp-sendfax",                   "hp-sendfax",         -300},

    // ── Networking / service discovery ──
    {"avahi-discover",               "avahi-discover",     -300},
    {"bssh",                         "bssh",               -300},
    {"bvnc",                         "bvnc",               -300},
    {"nm-connection-editor",         "nm-connection-editor", -200},
    {"wpa_gui",                      "wpa_gui",            -100},

    // ── Qt development / debugging ──
    {"assistant",                    "assistant",          -300},
    {"qt5-designer",                 "designer",           -300},
    {"qdbusviewer",                  "qdbusviewer",        -300},
    {"linguist",                     "linguist",           -300},

    // ── GTK development / debugging ──
    {"gtk3-demo",                    "gtk3-demo",          -300},
    {"gtk4-demo",                    "gtk4-demo",          -300},
    {"gtk3-icon-browser",            "gtk3-icon-browser",  -300},
    {"gtk4-icon-browser",            "gtk4-icon-browser",  -300},
    {"gtk-inspector",                "gtk-inspector",      -300},

    // ── D‑Bus / system introspection ──
    {"d-feet",                       "d-feet",             -300},
    {"lstopo",                       "lstopo",             -300},

    // ── Documentation / help viewers ──
    {"yelp",                         "yelp",               -200},
    {"khelpcenter",                  "khelpcenter",        -200},
    {"xman",                         "xman",               -300},
    {"man",                          "man",                -300},
    {"info",                         "info",               -300},

    // ── Special modes / tutorials ──
    {"vimtutor",                     "vimtutor",           -300},
    {"emacsclient-mail",             "emacsclient-mail",   -300},

    // ── ImageMagick GUI wrappers ──
    {"display",                      "display",            -300},
    {"import",                       "import",             -300},
    {"animate",                      "animate",            -300},

    // ── System logs / profiling ──
    {"gnome-logs",                   "gnome-logs",         -200},
    {"systemd-analyze",              "systemd-analyze",    -300},
    {"journalctl",                   "journalctl",         -300},
    {"powertop",                     "powertop",           -200},
    {"tcpdump",                      "tcpdump",            -300},
    {"strace",                       "strace",             -300},
    {"ltrace",                       "ltrace",             -300},
    {"valgrind",                     "valgrind",           -300},
    {"gdb",                          "gdb",                -300},

    // ── Distribution-specific / system administration (antiX/MX examples) ──
    {"",                             "bootrepair",         -200},
    {"",                             "chroot-rescue",      -200},
    {"",                             "live-usb-maker",     -200},
    {"",                             "remastersys",        -200},
    {"",                             "persist-config",     -200},
    {"",                             "persist-makefs",     -200},
    {"",                             "palimpsest",         -200},
    {"",                             "connectshares",      -200},
    {"",                             "disconnectshares",   -200},
    {"",                             "connectshares-config",-200},
    {"",                             "network-assistant",  -200},
    {"",                             "ceni",               -200},
    {"",                             "antix-wifi-switch",  -200},
    {"",                             "antix-cloud",        -200},
    {"",                             "antixradio",         -200},
    {"",                             "antix-faq",          -200},
    {"",                             "antix-updater",      -200},
    {"",                             "antix-viewer",       -200},
    {"",                             "antix-user-manager", -200},
    {"",                             "antix-init-diversity-manager", -200},
    {"",                             "choose-startup-services", -200},
    {"",                             "add-menu-item",      -200},
    {"",                             "remove-menu-item",   -200},
    {"",                             "refresh-menu",       -200},
    {"",                             "menu-editor",        -200},
    {"",                             "deb-installer",      -200},
    {"",                             "packageinstaller",   -200},
    {"",                             "repo-manager",       -200},
    {"",                             "formatusb",          -200},
    {"",                             "disk-manager",       -200},
    {"",                             "mountbox",           -200},
    {"",                             "backlight-brightness",-200},
    {"",                             "soundcard",          -200},
    {"",                             "alsamixer-equalizer",-200},
    {"",                             "speaker-test",       -200},
    {"",                             "bluetooth-transfer", -200},
    {"",                             "android-usb-connect",-200},
    {"",                             "nvidia-ddm-mx",      -200},
    {"",                             "galternatives",      -100},
    {"",                             "gnome-searchtool",   -100},
    {"",                             "command-line-control-centre", -200},
    {"",                             "control-centre",     -200},
    {"",                             "user-language",      -200},
    {"",                             "system-language",    -200},
    {"",                             "keyboard-layout",    -200},
    {"",                             "system-keyboard-qt", -200},
    {"",                             "set-font-size-dpi",  -200},
    {"",                             "login-manager",      -200},
    {"",                             "desktop-effects",    -200},
    {"",                             "conky-on-off",       -100},
    {"",                             "obconf",             -100},
    {"",                             "tint2conf",          -100},
    {"",                             "jgmenu",             -100},
    {"",                             "root-terminal",      -200},
    {"",                             "appkill",            -200},
    {"",                             "dinit-service-manager", -200},
    {"",                             "s6-rc-dialogbox-manager", -200},
    {"",                             "runit-service-manager", -200},
    {"",                             "startup-services",   -200},
    {"",                             "exit-desktop-session",-200},
    {"",                             "print-preview",      -100},
    {"",                             "yad-color",          -200},
    {"",                             "icon-browser",       -200},
    {"",                             "f3-qt",              -100},
    {"",                             "droopy",             -100},
    {"",                             "python3.13",         -200},
    {"",                             "groovy-console",     -100},
    {"",                             "search-google",      -200},
    {"",                             "search-wikipedia",   -200},
    {"",                             "search-duckduckgo",  -200},
    {"",                             "search-imdb",        -200},
    {"",                             "search-antix-forums",-200},
    {"",                             "search-mx-forums",   -200},
    {"",                             "search-gentoo-forums",-200},
    {"",                             "search-dictionary",  -200},
    {"",                             "search-start-page",  -200},
    {"",                             "search-bar",         -200},
    {"",                             "app-select",         -100},
    {"",                             "run",                -200},
    {"",                             "desktop-preferences",-200},
    {"",                             "session-file-manager",-200},
    {"",                             "shared-folders",     -100},
    {"",                             "pc-information",     -200},
    {"",                             "pointing-device-manager", -200},
    {"",                             "clear-recent-history", -100},
    {"",                             "enable-disable-pipewire", -200},
    {"",                             "quit-telegram",      -200},
    {"",                             "vscodium-url-handler", -200},
    {"",                             "toggle-xcompmgr",    -200}
};